- hosts: localhost
  vars:
    source_key: "./.ssh/ed25519_git"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/ed25519_git"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: SSH Setup
      include_tasks: tasks/ssh.yml
      args:
        apply:
          tags:
            - ssh
            - install
      tags:
        - always
    - name: Git Setup
      include_tasks: tasks/git-setup.yml
      args:
        apply:
          tags:
            - git
      tags:
        - always
    - name: .Dotfiles Setup
      include_tasks: tasks/dotfiles.yml
      args:
        apply:
          tags:
            - dotfiles
            - install
      tags:
        - always
    - name: Core Setup
      include_tasks: tasks/core-setup.yml
      args:
        apply:
          tags:
            - core
      tags:
        - always
    - name: Tools Setup
      include_tasks: tasks/tools.yml
      args:
        apply:
          tags:
            - tools
      tags:
        - always
    - name: Zsh Setup
      include_tasks: tasks/zsh-setup.yml
      args:
        apply:
          tags:
            - zsh
            - install
      tags:
        - always
    - name: Node Setup
      include_tasks: tasks/node-setup.yml
      args:
        apply:
          tags:
            - node
      tags:
        - always
      tags:
        - always
    - name: Nvim Setup
      include_tasks: tasks/nvim-setup.yml
      args:
        apply:
          tags:
            - nvim
            - install
      tags:
        - always
