- name: Install System Packages
  become: true
  apt:
    name: ["build-essential"]
  tags:
    - install

- name: Install System Packages (Neovim)
  become: true
  apt:
    name: ["ninja-build", "gettext", "libtool", "libtool-bin", "autoconf", "automake", "cmake", "g++", "pkg-config", "unzip", "curl", "doxygen"]
  tags:
    - install
  
- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "compton", "curl", "htop", "golang", "lsof", "i3", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "clangd", "ubuntu-mate-desktop" ]
  tags:
    - tbd

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - tbd

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - tbd

