- name: Install Volta
  shell: curl https://get.volta.sh | bash -s -- --skip-setup
  tags:
    - install

- name: Install Node
  shell: export VOLTA_HOME="$HOME/.volta" && export PATH="$VOLTA_HOME/bin:$PATH" && volta install node@14
  tags:
    - install

- name: Install Yarn
  shell: export VOLTA_HOME="$HOME/.volta" && export PATH="$VOLTA_HOME/bin:$PATH" && volta install yarn
  tags:
    - install
    - yarn

- name: Install Corepack
  npm:
    name: corepack
    global: yes
  tags:
    - tbd

- name: Install Yarn
  shell: corepack enable
  tags:
    - tbd

- name: Install eslint
  npm:
    name: eslint
    global: yes
  tags:
    - tbd
- name: Install VSCODE lang servers
  npm:
    name: vscode-langservers-extracted
    global: yes
  tags:
    - tbd
- name: install Python lang servers
  npm:
    name: npm install -g pyright
    global: yes
  tags:
    - tbd
- name: install svelte lang servers
  npm:
    name: npm install -g svelte-language-server
    global: yes
  tags:
    - tbd
- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - tbd
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags:
    - tbd
- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags:
    - tbd

