- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/dev/github.com/neovim/neovim"
  tags:
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make"
  # shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/dev/github.com/neovim/neovim && make install"
  tags:
    - neovim
- name: Neovim Plugin Development 1
  become: true
  apt: name=luarocks
  tags:
    - neovim
- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - neovim
- name: Install Vim-Plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - dotfiles
    - neovim
- name: Install Plugins
  shell: nvim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty
  tags:
    - dotfiles
    - neovim
