- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh
- name: Set authorized key took from file
  authorized_key:
    user: docker
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh
- name: Set Config
  copy:
    src: "./.ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    mode: 0644
  tags:
    - dotfiles
    - ssh
